### ISSUE TITLE
Event tracking with custom dimension and metric

### ISSUE THREAD

**Issue by LubosRemplik** [krizon/php-ga-measurement-protocol#25]
In javascript you can do something like this

<pre>ga('send', 'event', 'category', 'action', {
  'metric19': 24.99
});</pre>

I have try two ways how to approach this via PHP GA, 
Test 1:

<pre>$client->event(array(
  'cid' => 'customer id',
  'tid' => 'tracking id',
  'ec' => 'Event Category',
  'ea' => 'Event Action',
  'el' => array(
    'metric19' => '24.99'
  )
));</pre>

Test 2:

<pre>$client->event(array(
  'cid' => 'customer id',
  'tid' => 'tracking id',
  'ec' => 'Event Category',
  'ea' => 'Event Action',
  'el' => json_encode(array(
    'metric19' => '24.99'
  ))
));</pre>

it seems neither ones work.

Any ideas?

**Comment by gradosevic** [comment]
Custom dimensions and metrics should be sent in the same level as other parameters. Naming convention is cmX and cdX, e.g. cm1, cm2, cm3... and cd1, cd2, cd3...

For some reason, I am unable to receive custom data in my Analytics account, any example how to actually set up this would be much appreciated.
